appName=tomcat11

psiProbeVersion=3.7.3

tomcatVersion=11.0.22

waroverlayPluginVersion=0.9.3

#esupPublisherVersion=3.3.1
pronoteWSVersion=0.0.5-SNAPSHOT
#escoGLCVersion=2.1.0
#wisemappingVersion=5.0.21-recia-1.2.3
#escoCollabsoftVersion=0.4.2
#escoParamuseretabVersion=0.0.4
#siENTAPIVersion=0.1.1
serviceInfoAPIVersion=2.0.0
esidocAPIVersion=0.0.5-SNAPSHOT
mailAPIVersion=1.0.0
escoMediacentreVersion=0.0.7-SNAPSHOT
ressourcesDiffusablesVersion=1.0.1-SNAPSHOT
sympaAPIVersion=1.0.0
#restrictionRentreeVersion=1.0.3
#tabManagerVersion=0.0.2
esupFilemanagerVersion=6.0.0-SNAPSHOT-esco-1.0.5
pronoteApiVersion=0.0.1-SNAPSHOT

org.gradle.parallel=true
