subprojects {

    apply plugin: 'war'
    apply plugin: 'maven-publish'
    apply plugin: org.esco.script.gradle.plugins.GradleTomcatDeployPlugin

    task allDeps(type: DependencyReportTask)

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven {
            url "https://s01.oss.sonatype.org/content/groups/public/"
            mavenContent {
                snapshotsOnly()
            }
        }
        maven {
            url "https://nexus.recia.dev/repository/releases/"
        }
        maven {
            url "https://nexus.recia.dev/repository/snapshots/"
        }
    }

    configurations {
        overlay
        shell
        impexp
    }

    tasks.named('war') {

        from {
            configurations.overlay.collect { zipTree(it) }
        }

        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    artifacts {
        archives tasks.war
    }
}